#!/usr/bin/env python3
"""
generate_project_structure.py

Regenerates project_structure.txt: a tree view of the whole repository with
a line count next to every text file (or a size, for anything binary).

Run this after adding, removing, or renaming files so the copy linked from
the in-app Developer Guide (Help menu) stays accurate.

Usage:
    python generate_project_structure.py

Writes project_structure.txt next to this script (the repo root). Safe to
run any time -- it only reads the tree and overwrites that one output file.
"""

import os

# Folders that never belong in the tree: build output, caches, VCS internals.
# Keep this in sync with .gitignore.
IGNORED_DIRS = {
    '.git', '__pycache__', '.pytest_cache', 'build', 'dist',
    '.idea', '.vscode', 'venv', '.venv', 'env', 'node_modules',
}

# Individual files to skip -- OS cruft plus the output file itself (listing
# itself would make its own line count drift on every run).
IGNORED_FILES = {
    '.DS_Store', 'Thumbs.db', 'project_structure.txt',
}

# Extensions counted as text and given a line count. Anything else is
# reported by file size instead (binary, or not worth counting).
TEXT_EXTENSIONS = {
    '.py', '.txt', '.md', '.rst', '.json', '.csv', '.tsv', '.ini', '.cfg',
    '.yaml', '.yml', '.html', '.htm', '.css', '.qss', '.spec', '.iss',
    '.bat', '.sh', '.xml', '.svg', '.js',
}


def count_lines(path):
    try:
        with open(path, 'r', encoding='utf-8', errors='ignore') as f:
            return sum(1 for _ in f)
    except OSError:
        return None


def human_size(num_bytes):
    size = float(num_bytes)
    for unit in ('B', 'KB', 'MB', 'GB'):
        if size < 1024 or unit == 'GB':
            return f"{size:.0f}{unit}" if unit == 'B' else f"{size:.1f}{unit}"
        size /= 1024


def annotate(full_path, name):
    ext = os.path.splitext(name)[1].lower()
    if ext in TEXT_EXTENSIONS:
        n = count_lines(full_path)
        if n is not None:
            return f"{name} ({n} lines)"
    try:
        size = os.path.getsize(full_path)
        return f"{name} ({human_size(size)})"
    except OSError:
        return name


def walk(root, prefix=""):
    """Returns (list_of_display_lines, file_count, text_line_count)."""
    try:
        entries = sorted(os.listdir(root))
    except OSError:
        return [], 0, 0

    entries = [e for e in entries if e not in IGNORED_DIRS and e not in IGNORED_FILES]

    lines = []
    total_files = 0
    total_lines = 0

    for i, name in enumerate(entries):
        full = os.path.join(root, name)
        is_last = (i == len(entries) - 1)
        connector = "└── " if is_last else "├── "
        child_prefix = prefix + ("    " if is_last else "│   ")

        if os.path.isdir(full):
            lines.append(f"{prefix}{connector}{name}/")
            sub_lines, sub_files, sub_line_count = walk(full, child_prefix)
            lines.extend(sub_lines)
            total_files += sub_files
            total_lines += sub_line_count
        else:
            lines.append(f"{prefix}{connector}{annotate(full, name)}")
            total_files += 1
            ext = os.path.splitext(name)[1].lower()
            if ext in TEXT_EXTENSIONS:
                n = count_lines(full)
                if n:
                    total_lines += n

    return lines, total_files, total_lines


def main():
    repo_root = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(repo_root, "project_structure.txt")

    lines, total_files, total_lines = walk(repo_root)

    header = [
        "Project structure -- generated by generate_project_structure.py",
        f"Root: {repo_root}",
        f"Total files: {total_files}    Total lines (text files): {total_lines}",
        "",
    ]

    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(header + lines) + "\n")

    print(f"Wrote {out_path}")
    print(f"{total_files} files, {total_lines} lines of text total.")


if __name__ == "__main__":
    main()
